In [1]:
import pandas as pd
import numpy as np 

In [3]:
df = pd.read_csv('covid_toy.csv')
df.sample(5)

age  gender  fever   cough       city has_covid
52   47  Female  100.0  Strong  Bangalore       Yes
70   68  Female  101.0  Strong      Delhi        No
35   82  Female  102.0  Strong  Bangalore        No
31   83    Male  103.0    Mild    Kolkata        No
44   20    Male  102.0  Strong      Delhi        No

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:5],df.iloc[:,-1],test_size=0.2)

x_train.head(),y_test.shape

(    age  gender  fever   cough     city
 4    65  Female  101.0    Mild   Mumbai
 3    31  Female   98.0    Mild  Kolkata
 51   11  Female  100.0  Strong  Kolkata
 71   75  Female  104.0  Strong    Delhi
 80   14  Female   99.0    Mild   Mumbai,
 (20,))

## 1. Aam Zindagi

In [ ]:
# adding simple imputer to fever col
from sklearn.impute import SimpleImputer

si = SimpleImputer()

x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.fit_transform(x_test[['fever']])


x_train_fever

array([[ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [102.        ],
       [102.        ],
       [100.        ],
       [102.        ],
       [100.        ],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [100.67605634],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [100.67605634],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [100.67605634],
       [ 99.        ],
       [100.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [ 99.        ],
       [100.67605634],
       [102.        ],
       [103.        ],
       [101

In [ ]:
# Ordinalencoding -> cough
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Mild','Strong']])

x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])


x_train_cough.shape,x_test_cough.shape

((80, 1), (20, 1))

In [27]:
# OneHotEncoding -> gender,city
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first')

x_train_gender_city = ohe.fit_transform(x_train[['gender','city']]).toarray()
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']]).toarray()



x_train_gender_city.shape

(80, 4)

In [28]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# Also the test data Age
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape, x_test_age.shape

((80, 1), (20, 1))

In [ ]:
x_train_final = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

x_test_final = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)


x_train_final 

array([[ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 11.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 75.        ,  99.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 14.        , 104.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 48.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 84.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 24.        , 102.        ,   0.        ,   0.        ,
          0.    

## Mentos Zindagi

In [35]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

ct.fit_transform(x_train),
ct.fit_transform(x_test)



array([[104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  17.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [100.70588235,   1.        ,   1.        ,   0.        ,
          1.    